openapi: 3.2.0
info:
  title: Swiss Food Composition Database system configuration API
tags:
- name: system configuration
paths:
  /webresources/BLV-api/reloadCache:
    get:
      tags:
      - system configuration
      summary: Reload of the cache
      description: Reloads the local database cache of the application. Use in case of the faulty situations.
      operationId: reloadCache
      responses:
        '200':
          description: Indicator if cache reload completed successfully
          content:
            application/json:
              schema:
                type: boolean
